version: '3.7'

services:

  # database
  mysql:
    container_name: goose-mysql
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=goose
      - MYSQL_USER=goose
      - MYSQL_PASSWORD=1234

  # goose-api
  api:
    container_name: goose-api
    image: redgoose/goose-api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/goose/.env
      - ./data/upload:/goose/data/upload
    links:
      - mysql

  # phpmyadmin
  phpmyadmin:
    container_name: goose-myadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8010:80"
    environment:
      - PMA_HOST=mysql
      - PHP_UPLOAD_MAX_FILESIZE=100MB
      - PMA_USER=goose
      - PMA_PASSWORD=1234
    links:
      - mysql
